import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import project.connectionprovider;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author samma
 */
public class Admin_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Dashboard
     */
    public Admin_Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_settings1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btndelrecord = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnaddrecord = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btndelcustom = new javax.swing.JPanel();
        btnremcus = new javax.swing.JLabel();
        btnnewcustom = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btncusomerdetails = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btndashboard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_settings2 = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_settings1.setBackground(new java.awt.Color(78, 115, 239));
        btn_settings1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_settings1.setForeground(new java.awt.Color(255, 255, 255));
        btn_settings1.setText("Get Data");
        btn_settings1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_settings1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_settings1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 130, 30));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel3.setText("Payment Details");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, -1, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Meter ID", "Name", "Division", "Date Added"
            }
        ));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 510, 250));

        jTable2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Meter ID", "Total Payable", "Bill Month", "Due Date", "Late Payment"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 510, 250));

        btndelrecord.setBackground(new java.awt.Color(51, 51, 51));
        btndelrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Delete Record");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        btndelrecord.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        getContentPane().add(btndelrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 270, 50));

        btnaddrecord.setBackground(new java.awt.Color(51, 51, 51));
        btnaddrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Add Record");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        btnaddrecord.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        getContentPane().add(btnaddrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 270, 50));

        btndelcustom.setBackground(new java.awt.Color(51, 51, 51));
        btndelcustom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnremcus.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        btnremcus.setForeground(new java.awt.Color(255, 255, 255));
        btnremcus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnremcus.setText("Remove Consumer");
        btnremcus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnremcusMouseClicked(evt);
            }
        });
        btndelcustom.add(btnremcus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        getContentPane().add(btndelcustom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 270, 50));

        btnnewcustom.setBackground(new java.awt.Color(51, 51, 51));
        btnnewcustom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnewcustomMouseClicked(evt);
            }
        });
        btnnewcustom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Add New Consumer");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        btnnewcustom.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        getContentPane().add(btnnewcustom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 270, 50));

        btncusomerdetails.setBackground(new java.awt.Color(51, 51, 51));
        btncusomerdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncusomerdetailsMouseClicked(evt);
            }
        });
        btncusomerdetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Consumer's Details");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        btncusomerdetails.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        getContentPane().add(btncusomerdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 270, 50));

        btndashboard.setBackground(new java.awt.Color(51, 51, 51));
        btndashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dashboard");
        btndashboard.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        getContentPane().add(btndashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 270, 50));

        btn_settings2.setBackground(new java.awt.Color(78, 115, 239));
        btn_settings2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_settings2.setForeground(new java.awt.Color(255, 255, 255));
        btn_settings2.setText("Get Data");
        btn_settings2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_settings2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_settings2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, 130, 30));

        btn_logout.setBackground(new java.awt.Color(255, 51, 51));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Log Out");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 690, 130, 30));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel7.setText("Consumers Details");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin dashboard.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel5.setText("Consumer's Details");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login_Page().setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorAdded

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentShown

    private void btn_settings1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_settings1ActionPerformed
        // TODO add your handling code here:
        try
        {
            String sql = "select * from consumers";
            Connection con = connectionprovider.getCon();
            Statement st= con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                String MeterID = String.valueOf(rs.getString("MeterID"));
                String Name = String.valueOf(rs.getString("Name"));
                String Division = String.valueOf(rs.getString("Division"));
                String DateAdded = String.valueOf(rs.getString("DateJoined"));
                
                String tbData[] = {MeterID,Name,Division,DateAdded};
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                tblModel.addRow(tbData);
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Connection error" ); 
        }
    }//GEN-LAST:event_btn_settings1ActionPerformed

    private void btncusomerdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncusomerdetailsMouseClicked
        // TODO add your handling code here:
        new Consumer_Details().setVisible(true);
    }//GEN-LAST:event_btncusomerdetailsMouseClicked

    private void btnnewcustomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnewcustomMouseClicked
        // TODO add your handling code here:
        new Add_Consumer().setVisible(true);
    }//GEN-LAST:event_btnnewcustomMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new Consumer_Details().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new Add_Consumer().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnremcusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnremcusMouseClicked
        // TODO add your handling code here:
       new Delete_Consumer().setVisible(true); 
    }//GEN-LAST:event_btnremcusMouseClicked

    private void btn_settings2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_settings2ActionPerformed
        // TODO add your handling code here:
        try
        {
            String sql = "select * from consumerpayment";
            Connection con = connectionprovider.getCon();
            Statement st= con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                String MeterID = String.valueOf(rs.getString("MeterID"));
                String TotalPayable = String.valueOf(rs.getString("TotalPayable"));
                String BillMonth = String.valueOf(rs.getString("BillMonth"));
                String DueDate = String.valueOf(rs.getString("DueDate"));
                String LatePayment = String.valueOf(rs.getString("LatePayment"));
                
                String tbData[] = {MeterID,TotalPayable,BillMonth,DueDate,LatePayment};
                DefaultTableModel tblModel = (DefaultTableModel)jTable2.getModel();
                tblModel.addRow(tbData);
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Connection error" ); 
        }
    }//GEN-LAST:event_btn_settings2ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        new Add_Record().setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        new Delete_Record().setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_settings1;
    private javax.swing.JButton btn_settings2;
    private javax.swing.JPanel btnaddrecord;
    private javax.swing.JPanel btncusomerdetails;
    private javax.swing.JPanel btndashboard;
    private javax.swing.JPanel btndelcustom;
    private javax.swing.JPanel btndelrecord;
    private javax.swing.JPanel btnnewcustom;
    private javax.swing.JLabel btnremcus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
